#!/bin/bash

read -p "How many log lines should be shown? (More lines means more jitter during refreshes)" num
echo $num
if [ "$num" -le 0 ]
then
    num='30'
fi
echo "Limiting to $num lines!"

read -p "How frequently should I poll the remote? (in seconds)" period
if [ "$period" -le 0 ]
then
    period='1'
elif [ "$period" -ge 300 ]
then
    period='300'
fi
echo "Polling every $period seconds!"
 
# Loop to poll and display latest log (including remote, thanks to git fetch)
while :
do
    git fetch
    clear
    git --no-pager log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ci) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative --all -$num
    sleep $period
done
