#!/bin/bash

#command line options
#
# -l    number of lines to display
# -t    refresh time in seconds
# -s    whether or not to show git status as well
# -S    whether or not to show git story as well
#


function print_help {
    echo "--Git Livelog script--"
    echo "Usage:"
    echo "-h display help"
    echo "-t set refresh period (default is 60 seconds)"
    echo "-l set number of lines to display (default is 30 lines)"
    echo "-H [Y/n] whether or not to show the git history/logs"
    echo "-s [y/N] whether or not to show the git status"
    echo "-S [y/N] whether or not to show the git story"
    echo "-L [y/N] whether or not to show git list - your stories"

}

function is_int() { return $(test "$@" -eq "$@" > /dev/null 2>&1); } 


#set intelligent defaults
numlines='30'
refreshperiod='60'
showhistory=1
showstatus=0
showstory=0
showlist=0

#parse command line options, if there are any
if [ $# -gt 0 ] 
then
    #parse options
    while getopts "hl:H:t:s:S:L:" opt; do
      case "$opt" in
      h)
         print_help
         exit 0
         ;;
      t)
         if $(is_int "$OPTARG");
         then
               refreshperiod=$OPTARG
         else
               echo "bad value for option: -t"
               print_help
               exit 1
         fi
         ;;
      l)
         if $(is_int "$OPTARG");
         then
               numlines=$OPTARG
         else
               echo "bad value for option: -l"
               print_help
               exit 1
         fi
         ;;
      H)
         echo "OPTARG: $OPTARG"
         if [ "$OPTARG" == "n" ];
         then
            showhistory=0
            echo 'Will NOT show git history/logs'
         fi
         ;;
      s)
         echo "OPTARG: $OPTARG"
         if [ "$OPTARG" == "y" ];
         then
            showstatus=1
            echo 'Will show git status'
         fi
         ;;
      S)
         echo "OPTARG: $OPTARG"
         if [ "$OPTARG" == "y" ];
         then
            showstory=1
            echo 'Will show git story'
         fi
         ;;
      L)
         echo "OPTARG: $OPTARG"
         if [ "$OPTARG" == "y" ];
         then
            showlist=1
            echo 'Will show git list'
         fi
         ;;
      esac
    done
fi

# Loop to poll and display latest log (including remote, thanks to git fetch)
while :
do
    git fetch
    clear
    pwd

    # Dump the formatted git log
    if [ $showhistory -gt 0 ];
    then
      git --no-pager log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ci) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative --all -$numlines
    fi

    # Conditionally dump the git status
    if [ $showstatus -gt 0 ];
    then
       echo ''
       echo '##################################### STATUS ######################################'
       echo ''
       git status
    fi

    # Conditionally dump the git status
    if [ $showstory -gt 0 ];
    then
       echo ''
       echo '##################################### STORY  ######################################'
       echo ''
       git story
    fi

    # Conditionally dump the git status
    if [ $showlist -gt 0 ];
    then
       echo ''
       echo '#####################################  LIST  ######################################'
       echo ''
       git list
    fi
    sleep $refreshperiod
done
